twig:
    file_name_pattern: '*.twig'
    form_themes:
        - 'bootstrap_5_layout.html.twig'
    globals:
         categories: '@App\Service\GetCategories' 

when@test:
    twig:
        strict_variables: true
