#etapes 1 : faire en sorte de synchro le code avec le conteneur 

services:

  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: job
      MYSQL_USER: job
      MYSQL_PASSWORD: job
    volumes:
      - dbdata:/var/lib/mysql

    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: database
    ports:
      - "8081:80"
    depends_on:
      - database

volumes:
  dbdata: