controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

search_offres:
    path: /search
    controller: App\Controller\OffreController::search